personality = "pragmatic"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
[approvals]
mode = "auto"

[projects."/Users/neocortex/coding/gladis"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/gladis-hybrid"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/gladis-hybrid/analyst"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/schatzkarten-spiel"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/sks3"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/schatzkartenspiel"]
trust_level = "trusted"

[projects."/Users/neocortex/coding"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/glassnode-analyst/analyst"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/openglass"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/test"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/glassnode-cli"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/glassclaw"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/x-gladis"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/x-gladis-cc"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/ng-studio"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/metric-cat"]
trust_level = "trusted"

[projects."/Users/neocortex/coding/agentic-coding"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.3-codex-spark" = 3
